name: urbansearch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Conda
  - python=3.11
  - pytorch=2.6.0
  - pytorch-cuda=12.1
  - torchvision
  - pip
  - numpy<2.0
  # Pip
  - pip:
    - transformers==4.43
    - Pillow
    - matplotlib
    - jupyterlab
    - tqdm